dailyfresh/cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^add$', views.CartAddView.as_view(), name='add'), # 购物车记录添加
    url(r'^count', views.CartCountView.as_view(), name='count'), # 购物车总数
    url(r'^$', views.CartInfoView.as_view(), name='show'), # 购物车页面显示
    url(r'^update$', views.CartUpdateView.as_view(), name='update'), # 购物车记录更新
    url(r'^delete$', views.CartDeleteView.as_view(), name='delete'), # 购物车记录删除
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls', namespace='user')),     # 用户模块
    url(r'^tinymce/', include('tinymce.urls')),                 #tinymce
    url(r'^', include('goods.urls', namespace='goods')),        # 商品模块
    url(r'^search/', include('haystack.urls')),                 # haystack
    url(r'^cart/', include('cart.urls', namespace='cart')),     # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')),  # 订单模块
]

dailyfresh/goods/urls.py
from django.conf.urls import url
from goods import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'), # 首页
    url(r'^goods/(?P<goods_id>\d+)$', views.DetailView.as_view(), name='detail'), # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', views.ListView.as_view(), name='list'), # 列表页
]

dailyfresh/templates/search/search.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品搜索结果列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">{{ query }}</a>
		<span>></span>
		<a href="#">搜索结果如下:</a>
	</div>

	<div class="main_wrap clearfix">
        <ul class="goods_type_list clearfix">
            {% for item in page %}
                <li>
                    <a href="{% url 'goods:detail' item.object.id %}"><img src="{{ item.object.image.url }}"></a>
                    <h4><a href="{% url 'goods:detail' item.object.id %}">{{ item.object.name }}</a></h4>
                    <div class="operate">
                        <span class="prize">￥{{ item.object.price }}</span>
                        <span class="unit">{{ item.object.price}}/{{ item.object.unite }}</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>
            {% empty %}
                <p>无</p>
            {% endfor %}
        </ul>
        <div class="pagenation">
                {% if page.has_previous %}
				<a href="/search?q={{ query }}&page={{ page.previous_page_number }}"><上一页</a>
                {% endif %}
                {% for pindex in paginator.page_range %}
                    {% if pindex == page.number %}
				        <a href="/search?q={{ query }}&page={{ pindex }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="/search?q={{ query }}&page={{ pindex }}">{{ pindex }}</a>
                    {% endif %}

				{% endfor %}
                {% if spage.has_next %}
				<a href="/search?q={{ query }}&page={{ page.next_page_number }}">下一页></a>
                {% endif %}
			</div>
	</div>
{% endblock main_content %}
{% load staticfiles %}
{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $.get(
                '{% url 'cart:count' %}',
                function(data){
                    $('#show_count').text(data.total_count)
                }
            )
        })
    </script>
{% endblock%}

dailyfresh/templates/search/search2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
搜索的关键字:{{ query }}<br/>
当前页的Page对象:{{ page }}<br/>
分页paginator对象:{{ paginator }}<br/>
每页显示几条:{{ paginator.per_page }}<br/>

<ul>
    {% for item in page %}
        <li>{{ item.object.id }}-{{ item.object.name }}</li>
    {% endfor %}
</ul>

</body>
</html>